### ISSUE TITLE
ssl.CertificateError: hostname 'data.gateio.io' doesn't match either of 'gateio.io', 'www.gateio.io'

### ISSUE THREAD

**Issue by mymynew** [gateio/rest#12]
python3
urllib3-1.22
原来代码中data.gate.io访问超时，改成data.gateio.io就是下面这个异常。
`Traceback (most recent call last):
  File "D:\workcode\ai\code\python3\mytest\src\com\triangle-arbitrage-master\exchangeConnection\gateio\Client.py", line 30, in <module>
    print(gate_query.pairs())
  File "D:\workcode\ai\code\python3\mytest\src\com\triangle-arbitrage-master\exchangeConnection\gateio\gateAPI.py", line 22, in pairs
    return httpGet(self.__url, URL, params)
  File "D:\workcode\ai\code\python3\mytest\src\com\triangle-arbitrage-master\exchangeConnection\gateio\HttpUtil.py", line 24, in httpGet
    conn.request("GET", resource + '/' + params)
  File "D:\Program Files\Python\Python35\lib\http\client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "D:\Program Files\Python\Python35\lib\http\client.py", line 1152, in _send_request
    self.endheaders(body)
  File "D:\Program Files\Python\Python35\lib\http\client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "D:\Program Files\Python\Python35\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "D:\Program Files\Python\Python35\lib\http\client.py", line 877, in send
    self.connect()
  File "D:\Program Files\Python\Python35\lib\http\client.py", line 1261, in connect
    server_hostname=server_hostname)
  File "D:\Program Files\Python\Python35\lib\ssl.py", line 385, in wrap_socket
    _context=self)
  File "D:\Program Files\Python\Python35\lib\ssl.py", line 760, in __init__
    self.do_handshake()
  File "D:\Program Files\Python\Python35\lib\ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "D:\Program Files\Python\Python35\lib\ssl.py", line 646, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "D:\Program Files\Python\Python35\lib\ssl.py", line 305, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'data.gateio.io' doesn't match either of 'gateio.io', 'www.gateio.io'`

**Comment by mymynew** [comment]
在访问的地方加
import ssl
ssl.match_hostname = lambda cert, hostname: True
