### ISSUE TITLE
ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:777)

### ISSUE THREAD

**Issue by Chaology** [gateio/rest#2]
**It throws the error at times.** 

ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:777)

**经常运行时报错：**

ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:777)

**Comment by Chaology** [comment]
Traceback (most recent call last):
  File "notify.py", line 26, in <module>
    bid_book = gate.orderBook('eth_usdt')['bids']
  File "/Users/**/Desktop/Projects/gate/rest/python/gateAPI.py", line 54, in orderBook
    return httpGet(self.__url, URL, param)
  File "/Users/**/Desktop/Projects/gate/rest/python/HttpUtil.py", line 21, in httpGet
    conn.request("GET",resource + '/' + params )
  File "/Users/**/anaconda/envs/py36/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/**/anaconda/envs/py36/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/**/anaconda/envs/py36/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/**/anaconda/envs/py36/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/**/anaconda/envs/py36/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/**/anaconda/envs/py36/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Users/**/anaconda/envs/py36/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Users/**/anaconda/envs/py36/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Users/**/anaconda/envs/py36/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Users/**/anaconda/envs/py36/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:777)

**Comment by SilvesterHsu** [comment]
I got that problem too, but not often. It happened in `conn.request("GET",resource + '/' + params )`. Although I was unable to solve the SSLError, I used `urllib3` to take the place of `http.client`. I would pose my code later.

**Comment by Chaology** [comment]
@SilvesterHsu Great, is your code posted yet?

**Comment by SilvesterHsu** [comment]
@Chaology Yeah, over here. [HttpUtil.py](https://gist.github.com/SilvesterHsu/fc2d781bbe4dc583ce278d5271e4f87c#file-httputil-py-L18)
Overwrite the original `HttpUtil.py` file. Let me know if it works.

**Comment by hendra4ditya** [comment]
777
