### ISSUE TITLE
关于api服务器访问的几个问题。

### ISSUE THREAD

**Issue by cjrey-good** [gateio/rest#50]
几个问题请教一下。谢谢。
1、前几天有发marketlist使用时服务器timeout问题（timeout时间设置再大都报错），今天还是出现了。
报错信息如下：
  Traceback (most recent call last):
  File "D:/python_PJ/autoTradSys/Client.py", line 37, in <module>
    print(gate_query.marketlist())
  File "D:\python_PJ\autoTradSys\gateAPI.py", line 45, in marketlist
    return httpGet(self.__url, URL, params)
  File "D:\python_PJ\autoTradSys\HttpUtil.py", line 28, in httpGet
    data = response.read().decode('utf-8')
  File "C:\Python38\lib\http\client.py", line 461, in read
    return self._readall_chunked()
  File "C:\Python38\lib\http\client.py", line 571, in _readall_chunked
    value.append(self._safe_read(chunk_left))
  File "C:\Python38\lib\http\client.py", line 608, in _safe_read
    data = self.fp.read(amt)
  File "C:\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

Process finished with exit code 1

但是，如果我直接在浏览器中输入https://data.gateio.life/api2/1/marketlist，是可以正常响应的。
tickers的api也是同样问题。

2、同api服务器get或者post交互时，是否有显示服务器访问频率？如有的话，哪里可以看?

以上问题麻烦帮忙看一下，谢谢。

**Comment by revilwang** [comment]
1. 这是跟服务器之间网络连接不稳定造成的，如果 gateio.life 中断频率较高，可以尝试切换一下 data.gateio.ws 试试。
2. 现货的请求频率是300 rps，按源IP来识别的

**Comment by cjrey-good** [comment]
> 1. 这是跟服务器之间网络连接不稳定造成的，如果 gateio.life 中断频率较高，可以尝试切换一下 data.gateio.ws 试试。
> 2. 现货的请求频率是300 rps，按源IP来识别的

谢谢回复。
访问地址已经修改，访问次数改为每0.5秒1次，但是还是出现timeout的情况。
Traceback (most recent call last):
  File "D:/python_PJ/autoTradSys/Client.py", line 55, in <module>
    print(gate_query.ticker('btc_usdt')['last'])
  File "D:\python_PJ\autoTradSys\gateAPI.py", line 59, in ticker
    return httpGet(self.__url, URL, param)
  File "D:\python_PJ\autoTradSys\HttpUtil.py", line 26, in httpGet
    conn.request("GET", resource + '/' + params)
  File "C:\Python38\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Python38\lib\http\client.py", line 944, in send
    self.connect()
  File "C:\Python38\lib\http\client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1091: The handshake operation timed out

Process finished with exit code 1

**Comment by revilwang** [comment]
timeout 跟访问限制没有关系，单纯只是与服务端的网络不通畅。

几点改善建议：

1. 可以考虑使用代理服务器来访问 data.gate.io ，具体使用方式参考[这里](https://docs.python.org/zh-cn/3.6/library/http.client.html#http.client.HTTPConnection.set_tunnel)
2. 设置访问连接超时时间，即 `conn = http.client.HTTPConnection(timeout=30)` 
3. 捕获连接访问超时异常，在出现连接异常时尝试重试请求

**Comment by cjrey-good** [comment]
> timeout 跟访问限制没有关系，单纯只是与服务端的网络不通畅。
> 
> 几点改善建议：
> 
> 1. 可以考虑使用代理服务器来访问 data.gate.io ，具体使用方式参考[这里](https://docs.python.org/zh-cn/3.6/library/http.client.html#http.client.HTTPConnection.set_tunnel)
> 2. 设置访问连接超时时间，即 `conn = http.client.HTTPConnection(timeout=30)`
> 3. 捕获连接访问超时异常，在出现连接异常时尝试重试请求
好的 谢谢！我试一下。

**Comment by cjrey-good** [comment]
> timeout 跟访问限制没有关系，单纯只是与服务端的网络不通畅。
> 
> 几点改善建议：
> 
> 1. 可以考虑使用代理服务器来访问 data.gate.io ，具体使用方式参考[这里](https://docs.python.org/zh-cn/3.6/library/http.client.html#http.client.HTTPConnection.set_tunnel)
> 2. 设置访问连接超时时间，即 `conn = http.client.HTTPConnection(timeout=30)`
> 3. 捕获连接访问超时异常，在出现连接异常时尝试重试请求

好的 谢谢！ 我试一下。
